---
# tasks file for molecule-validate-nova-deploy

- import_tasks: cloning_openstack_ansible_ops.yml
- import_tasks: create_virtualenv_on_sut.yml
- import_tasks: run_openstack_service_setup_playbook.yml
- import_tasks: server_delete.yml
