---
# tasks file for molecule-validate-nova-deploy

- name: Find the proper inventory file
  shell: find /opt/openstack-ansible -name dynamic_inventory.py -print
  register: find_inventory_file
  ignore_errors: True

- name: Set proper inventory file
  set_fact:
    inventory_file: "{{ find_inventory_file.stdout }}"

- name: Run openstack-service-setup.yml playbook in virtualenv on SUT
  shell: |
    . /opt/molecule-test-env-on-sut/bin/activate
    ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i {{ inventory_file }} openstack-service-setup.yml
    deactivate
  args:
    executable: /bin/bash
    chdir: /opt/openstack-ansible-ops/multi-node-aio-xenial-ansible/playbooks/

- name: openstack-service-setup.yml was running successfully
  set_fact:
    openstack_service_setup_already_ran_successfully: true
