---
# tasks file for molecule-validate-nova-deploy

- name: Register utility container
  shell: |
    lxc-ls -1 | grep utility | head -n 1
  register: utility_container

- name: Check for servers
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack server list -c ID -f value'
  register: server_instances
  changed_when: false
  failed_when: false

- name: Delete all servers
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack server delete "{{ item }}"'
  when:
    - server_instances.rc == 0
    - server_instances.stdout != ""
  with_items: "{{ server_instances.stdout_lines }}"
